### ISSUE TITLE
Failure to authenticate due to empty string rawToken

### ISSUE THREAD

**Issue by solsson** [adohkan/git-remote-https-iap#7]
## Expected Behavior

Working git fetch and push

## Actual Behavior

During tireless retrying before your heroic rescue action on #5 one of our developers ended up in a state that causes all IAP requests to segfault in `parseJWToken`.

```
{"level":"debug","message":"Reading file /Users/me/.config/gcp-iap/my-example-net.cookie"}
{"level":"debug","message":"could not read IAP cookie for https://my.example.net: open /Users/me/.config/gcp-iap/me-example-net.cookie: no such file or directory"}
{"level":"debug","message":"GetCredentials - found credentials for protocol=iap,host=https://me.example.net,username=refresh-token"}
{"level":"debug","message":"GetIAPAuthToken - successfully used 'refresh_token' to claim IAP Auth Token"}
{"level":"debug","message":"rawToken: "}
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x0 pc=0x12e6e45]

goroutine 1 [running]:
github.com/adohkan/git-remote-https-iap/internal/iap.parseJWToken({0x0, 0xc0000274fc})
```

I think the segfault isn't the issue, but `"rawToken: "` is.

## Steps to Reproduce the Problem

We don't know yet but clearing the cookie file and re-configuring did not help.

Have you seen any instance of this issue, or have an immediate idea of where to look for the cause? If not I'll just continue digging 🙂 

## Specifications

  - Version: both v0.1.0 and v0.2.0
  - Git version: 2.30.1
  - Operating System: OSX 12.1

**Comment by ryanm101** [comment]
We've not seen it ourselves, If you check my PR the code changes for the fix were not huge. 

My primary change was to add a return to `handleIAPAuthCookieFor` of type `iap.Cookie` which enabled me to extract the `rawToken` and an extra param to `git.PassThruRemoteHTTPSHelper` to receive that token. 
cmd/git-remote-https+iap/main.go
internal/git/git.go

Nothing was changed in regards to getting or reading the token.

Your issue is occurring from https://github.com/adohkan/git-remote-https-iap/blob/d0ddf74f55f58f71a283276909d71a9a0f016145/internal/iap/cookie.go#L107 i think or in https://github.com/adohkan/git-remote-https-iap/blob/d0ddf74f55f58f71a283276909d71a9a0f016145/internal/iap/token.go#L107

**Comment by ryanm101** [comment]
I probably should put better error handling after https://github.com/adohkan/git-remote-https-iap/blob/d0ddf74f55f58f71a283276909d71a9a0f016145/cmd/git-remote-https%2Biap/main.go#L95 but not sure if that would do anything.. 

Curious to know how your dev managed to do get into that state.

**Comment by ryanm101** [comment]
I dont think it is related but some of our devs had a different issue and we had to recompile with `go1.18beta2`
to get this fix https://go-review.googlesource.com/c/go/+/353132/

**Comment by elatov** [comment]
@solsson did you end getting around this issue? I am seeing the same thing in my test setup and I am not sure why the token is coming back empty. Going through the browser works without any issues.

**Comment by solsson** [comment]
That sounds like exactly our case. No due to fatigue after #5 or other kinds of fatigue 😄 we decided we'll simply wipe that dev machine. Thus the only insight I can contribute is that it had nothing to do with the particular IAP account.

**Comment by elatovg** [comment]
So I think I tracked it down, at least what the issue was for me. Initially I just printed out the whole response and I saw this:

```bash
{"level":"debug","time":"2022-03-24T17:41:53-04:00","message":"GetCredentials - found credentials for protocol=iap,host=https://url,username=refresh-token"}
{"level":"debug","time":"2022-03-24T17:41:53-04:00","message":"Here is the refresh-token 1//0dN2q6LcQNHefxxx"}
{"level":"debug","time":"2022-03-24T17:41:53-04:00","message":"Here is the response &{400 Bad Request %!s(int=400) HTTP/2.0 %!s(int=2)
```

It looks like I am getting an HTTP 400 Code. Then after reading over [Programmatic authentication](https://cloud.google.com/iap/docs/authentication-howto#accessing_the_application), I ran the following:

```bash
> curl -v --data client_id=${DESKTOP_APP_CLIENT_ID} --data client_secret=${DESKTOP_APP_SECRET} --data refresh_token="1//0dN2q6LcQNHefxxx" --data grant_type=refresh_token --data audience=${WEB_IAP_CLIENT_ID} https://oauth2.googleapis.com/token
```

And I saw the following:

```bash
{
  "error": "invalid_audience",
  "error_description": "The audience client and the client need to be in the same project."
* Connection #0 to host oauth2.googleapis.com left intact
```

I think I accidentally specified the wrong **DESKTOP_APP_CLIENT_ID** from another project. So I reset up my credentials:

```bash
export WEB_IAP_CLIENT_ID=$(gcloud alpha iap oauth-clients list $(gcloud alpha iap oauth-brands list --format 'value(name)') --format 'value(name)' | awk -F/ '{print $NF}')
export DESKTOP_APP_CLIENT_ID="Client ID from the credentials page"
export DESKTOP_APP_SECRET="Client secret from the credentials page"
```

And deleted the existing refresh-token:

```bash
rm ~/.git-credentials
```

And then it started working. So it was a user error :). I'll try to open a pull request to check for the HTTP response code and possibly print out the message from the response to help troubleshoot this in the future.

**Comment by solsson** [comment]
Well done. I'd be ok with closing this issue at merge.

**Comment by elatov** [comment]
Sounds good. I'll wait for someone with write access to merge. Thank you.
